.Dd
.Dt SECRET 1
.Sh NAME
.Nm secret
.Nd Handle secrets with age encryption.
.Sh SYNOPSIS
.Nm
.Nm
.Fl g Ar entry
.Op field
.Nm
.Fl n Ar entry
.Nm
.Fl s Ar entry
.Sh DESCRIPTION
.Nm
is a POSIX utility to handle secrets using age encryption.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl g Ar entry Op prefix
Print
.Ar field
of
.Ar entry ,
or all fields of
.Ar entry
if
.Ar field
is not specified.
.It Fl n Ar entry
Create and modify new
.Ar entry .
.It Fl s Ar entry
Modify
.Ar entry .
.Sh ENTRIES
An
.Ic entry ,
when decrypted, is a file whose each line is a space-separated
.Dq name value
pair called a
.Ic field .
For example:
.Bd -literal -offset indent
username coolguy
password nicepass
.Bd
.Sh ENVIRONMENT VARIABLES
.Bl -tag -width Ds
.It Ev SECRET_PUBLIC_KEY
The age public key. This is mandatory.
.It Ev SECRET_PRIVATE_KEY_FILE
The age private key file. It is set to
.Pa ~/.age
by default.
.It Ev AGE
The age executable.
It is set to
.Pa age
by default.
.It Ev SECRET_DIR
The directory containing the entries.
It is set to
.Pa ~/.secrets
by default.
.El
