#!/bin/sh
set -eu

program="$0"

AGE=${AGE:-age}
SECRET_DIR=${SECRET_DIR:-~/.secrets}

error()
{
	echo "$1"
	exit 1
}

usage()
{
	u=$({
		echo "Usage: $program"
		echo "       $program -g entry [field]"
		echo "       $program -n entry"
		echo "       $program -s entry"
	})

	error "$u"
}

g=0
n=0
s=0

while getopts "g:n:s:" o
do
	case "$o" in
	g)
		g=1
		;;
	n)
		n=1
		;;
	s)
		s=1
		;;
	*)
		usage
		;;
	esac
done

shift $((OPTIND - 1))

[ $g -eq 1 ] && [ $# -gt 1 ] && usage
[ $g -eq 0 ] && [ $# -gt 0 ] && usage
