#!/bin/sh
set -eu

program="$0"

AGE=${AGE:-age}
SECRET_DIR=${SECRET_DIR:-~/.secrets}
SECRET_PRIVATE_KEY_FILE=${SECRET_PRIVATE_KEY_FILE:-~/.age}

error()
{
	echo "$1"
	exit 1
}

usage()
{
	u=$({
		echo "Usage: $program"
		echo "       $program -g entry [field]"
		echo "       $program -n entry"
		echo "       $program -s entry"
	})

	error "$u"
}

# Check for mandatory environment variables.
[ -z "${EDITOR:-}" ] && error "EDITOR is not set."
[ -z "${SECRET_PUBLIC_KEY:-}" ] && error "SECRET_PUBLIC_KEY is not set."

g=0
n=0
s=0
entry=''

while getopts "g:n:s:" o
do
	case "$o" in
	g)
		g=1
		entry="$OPTARG"
		;;
	n)
		n=1
		entry="$OPTARG"
		;;
	s)
		s=1
		entry="$OPTARG"
		;;
	*)
		usage
		;;
	esac
done

shift $((OPTIND - 1))

[ $g -eq 1 ] && [ $# -gt 1 ] && usage
[ $g -eq 0 ] && [ $# -gt 0 ] && usage

# Unflagged implementation.
[ $((g + n + s)) -eq 0 ] && [ -d "$SECRET_DIR" ] && ls "$SECRET_DIR"

# G flag imlpementation
if [ $g -eq 1 ]
then
	entry_file="$SECRET_DIR/$entry"

	[ -f "$entry_file" ] || error "Entry $entry does not exist."

	data=$("$AGE" -d -i "$SECRET_PRIVATE_KEY_FILE" "$entry_file")

	if [ -z "${1:-}" ]
	then
		echo "$data"
	else
		value=$(echo "$data" | grep "^$1 " \
		                     | sed 's/\s\+/ /g' \
		                     | cut -d ' ' -f 2)

		[ -z "$value" ] && error "Field $1 is not set."

		echo "$value"
	fi
fi
